# Generated by Django 3.0.5 on 2021-03-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_tile', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic.topic_tile+', to='forum.topic'),
        ),
    ]
