# Generated by Django 3.0.5 on 2021-03-13 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('forum', '0002_auto_20210313_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_tile',
            new_name='topic_title',
        ),
        migrations.AddField(
            model_name='post',
            name='topic_title',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='topic.topic_tile+', to='forum.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Userreg.id+', to='authapp.Userreg'),
        ),
    ]
