# Generated by Django 3.0.5 on 2021-03-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210313_1305'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
