# Generated by Django 3.0.5 on 2021-04-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
        migrations.CreateModel(
            name='subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_title', models.CharField(max_length=120)),
                ('sub_topic_description', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_id', to='forum.topic')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
