# Generated by Django 3.0.5 on 2021-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210313_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
