# Generated by Django 3.0.5 on 2021-04-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210415_1307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtopic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
