# Generated by Django 3.0.5 on 2021-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210415_1434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtopic',
            table='subtopic',
        ),
    ]
