# Generated by Django 3.0.5 on 2021-04-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20210415_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_title_post', to='forum.subtopic'),
        ),
    ]
