# Generated by Django 3.0.5 on 2021-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_topic_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pinned_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
