# Generated by Django 3.0.5 on 2021-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_topic_pinned_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='accepted_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='rejected_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
