# Generated by Django 3.0.5 on 2021-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20210415_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
