# Generated by Django 3.0.5 on 2021-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20210415_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='acceptedappeal_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='rejectedappeal_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
