# Generated by Django 3.0.5 on 2021-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20210417_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='logo.png', upload_to=''),
        ),
    ]
