# Generated by Django 3.0.5 on 2021-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_auto_20210417_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
