# Generated by Django 3.0.5 on 2021-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_topic_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
