# Generated by Django 3.0.5 on 2021-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_topic_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
