# Generated by Django 3.0.5 on 2021-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_auto_20210418_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='subtopic_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='subtopic_visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
