# Generated by Django 3.0.5 on 2021-04-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_kickedfromwebsite_kicked_by'),
        ('forum', '0033_auto_20210418_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emaillogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=200)),
                ('email_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to='authapp.Userreg')),
            ],
        ),
    ]
