# Generated by Django 3.0.5 on 2021-04-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_emaillogs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emaillogs',
            table='Emaillogs',
        ),
    ]
