# Generated by Django 3.0.5 on 2021-04-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_auto_20210420_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillogs',
            name='email_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emaillogs',
            name='email_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emaillogs',
            name='email_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
