# Generated by Django 3.1.6 on 2021-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0037_subtopiclatestposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
