# Generated by Django 3.0.5 on 2021-03-13 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('RoleName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='RoleName')),
            ],
            options={
                'db_table': 'userrole',
            },
        ),
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Useremail', models.CharField(max_length=100)),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('datecreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('Role', models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='UserRoles.RoleName+', to='authapp.UserRoles')),
            ],
            options={
                'db_table': 'useregister',
            },
        ),
    ]
