# Generated by Django 3.0.5 on 2021-04-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_kickedfromwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='banfromforum',
            name='banned_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='userbanforumby', to='authapp.Userreg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banfromgame',
            name='banned_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='userbangameby', to='authapp.Userreg'),
            preserve_default=False,
        ),
    ]
