# Generated by Django 3.1.6 on 2021-05-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0005_auto_20210506_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('subscription', models.BooleanField(default=1)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernewsid', to='authapp.userreg')),
            ],
            options={
                'db_table': 'emailnews',
            },
        ),
        migrations.CreateModel(
            name='unsubscribefeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackname', models.CharField(max_length=250)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('emailnewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailnewsid', to='home.emailnews')),
            ],
            options={
                'db_table': 'unsubscribefeedback',
            },
        ),
    ]
