# Generated by Django 3.1.6 on 2021-05-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210506_1635'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsbanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernewsupdate', to='authapp.userreg')),
            ],
        ),
    ]
