# Generated by Django 3.0.5 on 2021-04-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0004_kickedfromwebsite_kicked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode_Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_Avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Accuracy_Avg', models.DecimalField(decimal_places=3, max_digits=4)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserI', to='authapp.Userreg')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Shot', models.CharField(max_length=200)),
                ('Hit', models.CharField(max_length=200)),
                ('Score', models.PositiveIntegerField(default=0)),
                ('Accuracy', models.FloatField(default=0)),
                ('Game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', to='nonmotiongame.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Game_Mode_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game_Mode', to='nonmotiongame.Game_Mode'),
        ),
        migrations.AddField(
            model_name='game',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserG', to='authapp.Userreg'),
        ),
    ]
