# Generated by Django 3.0.5 on 2021-04-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='Accuracy_Avg',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Score_Avg',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
