# Generated by Django 3.0.5 on 2021-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0005_auto_20210419_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Hits_Avg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='Shots_Avg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
