# Generated by Django 3.0.5 on 2021-04-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0006_auto_20210420_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank_Name', models.CharField(max_length=150)),
                ('Rank_description', models.CharField(max_length=250)),
                ('Rank_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
