# Generated by Django 3.0.5 on 2021-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0011_auto_20210420_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='forumpoints',
            field=models.CharField(default=100, max_length=150),
            preserve_default=False,
        ),
    ]
