# Generated by Django 3.0.5 on 2021-04-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_kickedfromwebsite_kicked_by'),
        ('nonmotiongame', '0012_user_info_forumpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='userproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='nonmotiongame.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproducts', to='authapp.Userreg')),
            ],
            options={
                'db_table': 'userproducts',
            },
        ),
    ]
