# Generated by Django 3.0.5 on 2021-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0014_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
