# Generated by Django 3.0.5 on 2021-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0016_auto_20210423_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_spriteimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
