# Generated by Django 3.0.5 on 2021-04-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonmotiongame', '0017_products_product_spriteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
